### ISSUE TITLE
versions:display-plugin-updates does not understand maven-enforcer-plugin

### ISSUE THREAD

**Issue by caseboltj** [mojohaus/versions-maven-plugin#48]
(This is more of a "did this tracker get lost in the transition to mojohaus" tracker than a new issue...)

I removed the deprecated prerequisites stanza from my POM in favor of using the enforcer plugin.

Now, when running versions:display-plugin-updates, existing updates are not found and a message is displayed stating that I need to add the prereqs info back into the POM.

According to http://stackoverflow.com/questions/29344809/versionsdisplay-plugin-updates-does-not-understand-maven-enforcer-plugin , there was a tracker (MVERSIONS-272) on codehaus for this issue.

I searched open and closed trackers here at mojohaus, and did not find anything.

Did the original tracker get closed, or did it just miss the transition?

**Comment by informatik01** [comment]
Here is the archived version of that issue page:
https://web.archive.org/web/20150514123930/http://jira.codehaus.org/browse/MVERSIONS-272

**Comment by brunchboy** [comment]
Yes, it seems that I am now in a damned-if-I-do, damned-if-I-don’t situation. I have added the enforcer plugin, but if I leave the prerequisites stanza in my `pom.xml` then I get a warning about it being deprecated when I build, and if I omit it, I get an error when I try to run `versions:display-plugin-updates`. Is there a correct answer?

**Comment by khmarbaise** [comment]
The current version (2.3) of versions-maven-plugin does not correctly handle that. The correct way since Maven 3 is to remove the prerequisites for non-plugin projects. But the problem is located in the versions-maven-plugin.

**Comment by ptamarit** [comment]
Hi,

If this can help, here are some example with Maven v3.5.0 and versions plugin v2.4 using the command `mvn versions:display-plugin-updates`:
* Using prerequisites triggers a Maven warning but is well understood by the versions plugin.
* Using enforcer works well with Maven but triggers an error with the versions plugin.

[pom-prereq.txt](https://github.com/mojohaus/versions-maven-plugin/files/1059104/pom-prereq.txt)
[out-prereq.txt](https://github.com/mojohaus/versions-maven-plugin/files/1059105/out-prereq.txt)
[pom-enforcer.txt](https://github.com/mojohaus/versions-maven-plugin/files/1059106/pom-enforcer.txt)
[out-enforcer.txt](https://github.com/mojohaus/versions-maven-plugin/files/1059107/out-enforcer.txt)

Cheers,
Pablo

**Comment by garretwilson** [comment]
> Is there a correct answer?

@brunchboy , no, apparently not. @dannil gave a good summary here: https://github.com/mojohaus/versions-maven-plugin/issues/173#issuecomment-320097656

**Comment by brunchboy** [comment]
Sigh, indeed, I keep hoping a fixed version of the plugin will be released, but have been disappointed so far.

**Comment by PascalSchumacher** [comment]
A fix would be very nice as this is very confusing. :(

**Comment by adamvoss** [comment]
Confusingly, the plugin even tells me to use the enforcer despite not respecting the setting:

```
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain maven-enforcer-plugin to
[ERROR] force the maven version which is needed to build this project.
[ERROR] See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
```

**Comment by PascalSchumacher** [comment]
A release containing this would be highly appreciated.

**Comment by garretwilson** [comment]
So is this fixed now?

**Comment by PascalSchumacher** [comment]
@garretwilson It works for me when I use versions-maven-plugin `2.7`.

**Comment by garretwilson** [comment]
Woohoo! Yeah, I just tried it. I had to add the Maven Enforcer Plugin indicating a minimum Maven version of 3.0.5, but then it worked and I didn't have to use that incorrect `<prerequisites>` tag anymore. Thanks so much everyone!!

**Comment by brunchboy** [comment]
@garretwilson I am not having the same luck, I still get the complaints about missing prerequisites even after adding explicit entries for `versions-maven-plugin` `2.7` and `maven-enforcer-plugin` `3.0.0-M2` configured to `requireMavenVersion` `3.0.5` (my Maven version is actually 3.5.4). What am I missing?

**Comment by garretwilson** [comment]
You might try looking at the latest version of our [GlobalMentor parent POM](https://bitbucket.org/globalmentor/globalmentor-parent/src/master/pom.xml) I just updated it this morning to [fix this problem](https://globalmentor.atlassian.net/browse/JAVA-67). We haven't yet released his artifact to Maven Central, so if you find a problem in it let me know! Hopefully it will point you to what you're missing—or indicate something I missed.

**Comment by caseboltj** [comment]
Thanks everyone for staying on this!  As the originator of this issue, I can report that the fix is working as advertised for me.

**Comment by cowwoc** [comment]
Another thing to watch out for is that your enforcer execution should have an id of `enforce-maven` as mentioned at https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html as opposed to `enforce-versions` as mentioned at https://maven.apache.org/enforcer/maven-enforcer-plugin/usage.html. It's unfortunate that the enforcer's own documentation gets it wrong.

**Comment by brunchboy** [comment]
Interesting, what cares about the id?

**Comment by cowwoc** [comment]
@brunchboy My understanding of this is a bit fuzzy but going by https://maven.apache.org/guides/mini/guide-default-execution-ids.html each plugin has a default execution id. If you want to override its default configuration (for example, by default the enforcer plugin does nothing) then you must specify the execution id you're trying to override. That way if a user invokes an unrelated task (e.g. `mvn clean install` ... notice that they didn't explicitly invoke enforcer) then when the enforcer plugin runs it'll use your overridden configuration.

I hope that helps.

**Comment by onacit** [comment]
@caseboltj Which `fix` were you mention?

**Comment by jakub-bochenski** [comment]
The plugin documentation wasn't updated and it still talks about "taking care of Maven version prerequisites."

**Comment by davewichers** [comment]
I'm running into this exact problem (even though this issue is supposed to be fixed). Here is the output I'm seeing when running "mvn versions:display-plugin-updates":

[INFO] --- versions-maven-plugin:2.8.1:display-plugin-updates (default-cli) @ antisamy ---
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[INFO] All plugins have a version specified.
[INFO] 
[INFO] Project inherits minimum Maven version as: 3.2.5
[INFO] Plugins require minimum Maven version of: 3.3.9
[INFO] 
[ERROR] Project requires an incorrect minimum version of Maven.
[ERROR] Update the pom.xml to contain maven-enforcer-plugin to
[ERROR] force the Maven version which is needed to build this project.
[ERROR] See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[ERROR] Using the minimum version of Maven: 3.2.5
[INFO] 
[INFO] Require Maven 3.3.9 to use the following plugin updates:
[INFO]   com.github.spotbugs:spotbugs-maven-plugin ...... 4.5.2.0 -> 4.5.0.0
[INFO]   org.jacoco:jacoco-maven-plugin .............................. 0.8.7

To address this issue, I added a requireMavenVersion block to my existing <build> maven-enforcer-plugin configuration like so:

                    <execution>
                        <id>enforce-maven</id>
                        <goals><goal>enforce</goal></goals>
                        <configuration>
                            <rules>
                                <requireMavenVersion>
                                    <version>3.3.9</version>
                                </requireMavenVersion>
                            </rules>
                        </configuration>
                    </execution>

I'm actually using Maven version 3.8.4, so I tested the above to make sure it works, but setting the required version to 3.8.5 (which doesn't exist yet), and then ran "mvn test", which reports:

[INFO] --- maven-enforcer-plugin:3.0.0:enforce (enforce-maven) @ antisamy ---
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequireMavenVersion failed with message:
Detected Maven Version: 3.8.4 is not in the allowed range 3.8.5.

So, my <requireMavenVersion> config is working just fine, but when I run: "mvn versions:display-plugin-updates" it is still complaining that I don't enforce a proper minimum Maven version. I still get the exact same error. Either I'm doing something wrong, or there is still a bug in the versions-maven-plugin related to this issue.

**Comment by onacit** [comment]
Is this problem fixed, really?

**Comment by cowwoc** [comment]
@onacit Run this plugin using the `-X` debug switch and look for a line starting with `MinimalMavenBuildVersionFinder`. If you then cross-reference that line with one of the lines in this method you'll figure out what is wrong: https://github.com/mojohaus/versions/blob/master/versions-maven-plugin/src/main/java/org/codehaus/mojo/versions/MinimalMavenBuildVersionFinder.java#L52

Good luck!
